language: node_js

node_js:
  - '6'

script: npm run cover

after_script:
  - cat ./tests/coverage/lcov.info | ./node_modules/.bin/coveralls

before_deploy: npm run compile
deploy:
  provider: npm
  skip_cleanup: true
  on:
    tags: true
    node: '6'
  email: adminlogin@ssense.com
  api_key:
    secure: KeheoeN1J1eAW4gSmVvSgFE98DL8URNSkSXNJt09kyk5eGFngojNNUy74nDiupCDvlMNnh/IGTi3FmVpI5N1IAkkrqH+IyR8Lv7FfRneKwZof0h8iZOpo/I1rquOEmOkb2dlwTcHGar9aSWxEvcs79HlrDsTO1UnkV9f9/htzrppIFJOztMco6el5+9Mf2MMzjj2s7SeJsZfJqmZ2MNEQdkcyIRscrtzyIdTlTG4QxPeMf2b7fXP19XDdFUUhDXqMqGnsaaRLTjCzrTRDQkbLWV7qkmZAQB+/KChUDBZTpl3fL+skuq1LorpKELEFBpJnZ2aRSxOo/9HgLTiyb5ZlAqIg2d1G08pUO1nPR9AMMtFz9lIN8qMw1mPSAQ/S5Jh7sXJbO7qlXF2l2xlwd+xTaOrE/Loi3tSFTj8YfCgYnigBxt1YD1eh/UAB4NZ5OYxlYoGw5NCQekkw3quXWxo7Xpi5RNa3jLgXQFQGClTkEdL0QXkT8pnOYNkpcw5B8VlvcKrFSKJUlYa9DFybPHH5oCnqx+9vN5rW5xag+3ne8Rr1WYdjIXGNWUJCIrc5QoQYn9O57xtqJuE+N8OFu4W1yPWG5kaSDwpienTz8gEmsT2VxhAy/0Uc7gIelvp6r7tlgDAtySLoH1d/DsFx7TjoC3TMlpi6dl5C/Epa1ZB5Lk=
